development:
  adapter: postgresql
  database: stringer_dev
  encoding: unicode
  pool: 5

test:
  adapter: sqlite3
  database: db/stringer_test.sqlite

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dbibra39e733iq
  username: trfoajmntjazdy
  password: ufLWnpJfMlDygGunJ5YdlpVJwA
  host: ec2-54-243-51-102.compute-1.amazonaws.com
  port: 5432
