development:
  adapter: postgresql
  database: stringer_dev
  encoding: unicode
  pool: 5

test:
  adapter: sqlite3
  database: db/stringer_test.sqlite

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dbibra39e733iq
  username: bjjtxhuqcemetk
  password: qapOhCoSMPmrRp8kVYFRgI1eiP
  host: ec2-54-221-206-165.compute-1.amazonaws.com
  port: 5432
